### ISSUE TITLE
broken link on public website | fact-sheets/licenses.md

### ISSUE THREAD

**Issue by robbiemorrison** [opendatalu/datagouvlu-pages#2]
This link is broken on your public website:
- https://data.public.lu/fact-sheets/licenses.md

It returns a 404 error.  As of the time of this issue.

**Comment by AlainVagner** [comment]
Thanks for the information! The URL of the page is now https://data.public.lu/en/pages/fact-sheets/licenses/
The fix will be available on the website in a few minutes.

**Comment by robbiemorrison** [comment]
Many thanks for the information.  And I can confirm the URL works.  You can mark this issue closed.
